@extends('layouts.app')

@section('title', 'Play Game - Vier op een Rij')

@section('content')
<div class="game-container">
    <div class="difficulty-selection" id="difficultySelection">
        <h2>Select Difficulty</h2>
        <div class="difficulty-buttons">
            <button class="difficulty-btn" data-difficulty="EASY">EASY</button>
            <button class="difficulty-btn" data-difficulty="MEDIUM">MEDIUM</button>
            <button class="difficulty-btn" data-difficulty="HARD">HARD</button>
        </div>
    </div>

    <div class="game-board-container" id="gameBoardContainer" style="display: none;">
        <div class="game-info">
            <div class="turn-indicator" id="turnIndicator">
                <span class="player-indicator">Your Turn</span>
            </div>
            <div class="game-stats">
                <span>Difficulty: <strong id="selectedDifficulty">-</strong></span>
                <span>Turns: <strong id="turnCount">0</strong></span>
            </div>
            <button class="btn-reset" id="resetButton">New Game</button>
        </div>

        <div class="game-board" id="gameBoard">
            <!-- 7 columns x 6 rows grid will be generated by JavaScript -->
        </div>

        <div class="game-message" id="gameMessage" style="display: none;">
            <h2 id="messageText"></h2>
        </div>
    </div>

    <!-- High Score Submission Form -->
    <div class="high-score-form" id="highScoreForm" style="display: none;">
        <h2>Congratulations! You Won!</h2>
        <p>Submit your score to the leaderboard</p>
        <form action="{{ route('scores.store') }}" method="POST">
            @csrf
            <input type="hidden" name="turns" id="formTurns">
            <input type="hidden" name="difficulty" id="formDifficulty">

            <div class="form-group">
                <label for="playerName">Your Name:</label>
                <input type="text" id="playerName" name="name" required maxlength="100" placeholder="Enter your name">
            </div>

            <div class="form-stats">
                <p>Turns taken: <strong id="displayTurns">-</strong></p>
                <p>Difficulty: <strong id="displayDifficulty">-</strong></p>
            </div>

            <button type="submit" class="btn-submit">Save Score</button>
        </form>
    </div>
</div>
@endsection
